### ISSUE TITLE
Vue Getting Started guide missing required sass installs

### ISSUE THREAD

**Issue by 3dfoster** [carbon-design-system/carbon-website#90]
## Detailed description

> Describe in detail the issue you're having.

The guide at [https://www.carbondesignsystem.com/getting-started/developers/vue](https://www.carbondesignsystem.com/getting-started/developers/vue) only mentions `@carbon/vue` as a required install, but `sass-loader` and `node-sass` are also required for `npm run serve` to work.

> Is this issue related to a specific component?

It's related to the previously mentioned guide.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected `npm run serve` to build the Vue app right away. Instead I read through the error messages and found out I was missing two NPM packages. I'd like the getting started guide to include those packages.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

My IBM Cloud platform team uses carbon components for our UI and I'm trying to learn how to integrate Carbon into a new project.

## Steps to reproduce the issue

1. Follow instructions at [https://www.carbondesignsystem.com/getting-started/developers/vue](https://www.carbondesignsystem.com/getting-started/developers/vue)
2. on `npm serve` error messages will appear for missing packages.

## Additional information

Here are the errors I received in terminal:

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.sassLoader (/Users/david/Workspace/carbon/node_modules/sass-loader/lib/loader.js:46:72)
```

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.sassLoader (/Users/david/Workspace/carbon/node_modules/sass-loader/lib/loader.js:46:72
```

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
